import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getProducts } from "../utils/shopify";
import ProductCard from "../components/ProductCard/ProductCard";
import Header from "../components/Header/Header";

export default function Home({ data }) {
  const products = data.products.edges;
  return (
    <>
      <Head>
        <title>Nextjs Shopify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <div className={styles.products}>
          {products.map((product) => {
            return <ProductCard key={product.node.id} product={product} />;
          })}
        </div>
      </main>
    </>
  );
}
export const getServerSideProps = async () => {
  const data = await getProducts();
  return {
    props: { data },
  };
};
